# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-03-12 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='cost_field',
            field=models.FloatField(default=None, null=True),
        ),
    ]
